### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by tangyuelm** [akshay-k2/m5#2]
Dear Authors,

Thank you for the codes and I am very interested in your work. However, when I tried to run the code, I met an error of

Traceback (most recent call last):
  File "E:/FPGAPro/m5-main/src/eval_topo_orders.py", line 49, in <module>
    def gen_topo_orders(G: nx.DiGraph, topo_order_functions: dict[str, Union[Callable, partial]]) -> dict[str, list]:
TypeError: 'type' object is not subscriptable

I am wondering if anyone can help me to debug for this problem. Thank you.

**Comment by tangyuelm** [comment]
It seems that the dict[str, int] causes the problem in my current Python version. I used Python 3.7. Could you also let me know what version is prefered? Thank you.

**Comment by tangyuelm** [comment]
I used Python3.10 but got the following errors after running for a while. Could you provide any suggestions? Besides, how long will it take to generate the results for a model like VLocNet? Thank you.

Traceback (most recent call last):
  File "/mnt/e/ty/FPGApro/m5-main/src/eval_topo_orders.py", line 408, in <module>
    best_mappings = find_best_mappings(DG, topo_order_functions, II, DSP_total, acc_config_enable, T, n_jobs=N_JOBS)
  File "/mnt/e/ty/FPGApro/m5-main/src/eval_topo_orders.py", line 83, in find_best_mappings
    optimal_mappings = compute_optimal_mappings(graph, topo_orders, II, DSP, acc_config_enable, T, n_jobs=n_jobs)
  File "/mnt/e/ty/FPGApro/m5-main/src/eval_topo_orders.py", line 65, in compute_optimal_mappings
    optimal_mappings[ordering] = Parallel(n_jobs=n_jobs)(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/joblib/parallel.py", line 1952, in __call__
    return output if self.return_generator else list(output)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/joblib/parallel.py", line 1595, in _get_outputs
    yield from self._retrieve()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/joblib/parallel.py", line 1699, in _retrieve
    self._raise_error_fast()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/joblib/parallel.py", line 1734, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/joblib/parallel.py", line 736, in get_result
    return self._return_or_raise()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/joblib/parallel.py", line 754, in _return_or_raise
    raise self._result
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGKILL(-9)}

**Comment by stefanpie** [comment]
Hello, and thank you for submitting your issue! Sorry, I have not had time to reply this week since I have been away at a conference.

**Type Hint Errors**

For the type hint errors, you seem to have figured out the right solution. I believe the type hint syntax I was using was not supported in Python 3.7 but upgrading like you did to Python 3.10 should resolved (and did seem to resolve) this issue.

**Joblib Issue**
This is more ticky to debug as there could be may causes. If you can provide a reproduced test case of your script or workflow when running this, that would help me a lot in debugging. I will also look into this in more depth next week as well and get back to you if I find anything. A quick fix, for now, is to try a different backend like multiprocessing or threading (you can edit the job lib parallel call to pass in a different backend for the parallel executor) or set n_job=1 to run everything sequentially and not use any parallelism backend.

**Comment by tangyuelm** [comment]
Thank you for the reply. I tried both n_job=-1 and 1, while the killing still happened. I ran them on my wsl with Ubuntu 22.04 and Python 3.10.12. I also closed other programs. Here is the screenshot. 
![image](https://github.com/akshay-k2/m5/assets/58452529/c9c63053-64aa-447c-9503-a56c22bd4965)
I also attached the output file. 
[eval_topo_ordersCASUA_SURF.txt](https://github.com/akshay-k2/m5/files/13254566/eval_topo_ordersCASUA_SURF.txt)
I have not made too many modifications to the main file. I just added the following configurations
![image](https://github.com/akshay-k2/m5/assets/58452529/5bc9c4e0-0eaf-49ff-8e3a-93b2ec1c21b5)

**Comment by stefanpie** [comment]
Like mentioned previously, try a different Joblib backend in the `Parallel` call from Joblib. I would suggest trying multiprocessing first.

I have a feeling that it might also have somthing to do with WSL. Do you have any way to easily run these evaluations in an environment that is not inside WSL? If so I would also give that a try. I have never tried using something like Joblib in a virtual environment. I would not expect there to be any issues but it could be a possibility.

The error trace is not super helpful so I will have to try and reproduce these results by running the program itself if nothing else works. I can try to do this tomorrow or Wednesdays depending on when I get the time.

**Comment by tangyuelm** [comment]
Thank you for your time and help. I have tried to change the “loky” into "multiprocessing" but still got killed. I also tried my labmate's linux system which is ubuntu22.04. I also tried some other ubuntu servers before but still get the same killing problem.

**Comment by tangyuelm** [comment]
I also find a redhat platform on aws c6i.32xlarge instance which is equipped with 128 vCPUs and 256GB Mem. The VLocNet case can be completed within a few minutes, but when I try to run other cases like CASUA_SURF, FaceBag, and VFS, the program is killed after running an hour. I have attached the configuration of the platform I use now.
![image](https://github.com/akshay-k2/m5/assets/58452529/be563d82-c8ab-49bb-b6d2-7b49febdd731)
![image](https://github.com/akshay-k2/m5/assets/58452529/c8f20681-d719-4f90-a57b-5c014de4718e)

**Comment by stefanpie** [comment]
Thank you for the information; that is helpful. I'm still looking into this right now but nothing new yet. Let me know if you have an urgent deadline you need this to work for.

**Comment by tangyuelm** [comment]
Thank you for your attention. It would be really helpful if I could make it before the 20th. After the 20th, I will not have any urgent deadline. Thank you.
